trigger: none

parameters:
  - name: aksServiceConnection
    type: string
    displayName: "AKS Service Connection"
    default: thevindu-aks-sc

  - name: azureServiceConnection
    type: string
    displayName: "Azure Resource Manager Service Connection"
    default: thevindu-rnd-sc

  - name: vmssResourceGroup
    type: string
    displayName: "VMSS Resource Group"
    default: rg-thevindu

  - name: vmssName
    type: string
    displayName: "VMSS Name"
    default: is-vmss

  - name: vmssInstanceId
    type: string
    displayName: "VMSS Instance ID"
    default: "0"

  - name: namespace
    type: string
    displayName: "Kubernetes Namespace"
    default: kube-system

stages:
  - stage: Destroy
    displayName: Destroy NetProbe
    jobs:
      - job: DestroyNetProbe
        displayName: helm uninstall netprobe
        pool:
          name: rnd-thevindu-vmss
        steps:
          - checkout: none

          - task: HelmDeploy@0
            displayName: Helm uninstall
            continueOnError: true
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: ${{ parameters.aksServiceConnection }}
              namespace: ${{ parameters.namespace }}
              command: uninstall
              arguments: netprobe

          - task: Kubernetes@1
            displayName: Confirm resources removed
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: ${{ parameters.aksServiceConnection }}
              namespace: ${{ parameters.namespace }}
              command: get
              arguments: 'pods,daemonsets -l app.kubernetes.io/name=netprobe --ignore-not-found'
              outputFormat: ''
