trigger: none

parameters:
  - name: aksServiceConnection
    type: string
    displayName: "AKS Service Connection"
    default: rnd-aks-thevindu

  - name: namespace
    type: string
    displayName: "Kubernetes Namespace"
    default: kube-system

stages:
  - stage: Destroy
    displayName: Destroy NetProbe
    jobs:
      - job: DestroyNetProbe
        displayName: helm uninstall netprobe
        pool:
          name: rnd-thevindu-vmss
        steps:
          - checkout: none

          - task: HelmDeploy@0
            displayName: Helm uninstall
            continueOnError: true
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: ${{ parameters.aksServiceConnection }}
              namespace: ${{ parameters.namespace }}
              command: uninstall
              arguments: netprobe

          - task: Kubernetes@1
            displayName: Confirm resources removed
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: ${{ parameters.aksServiceConnection }}
              namespace: ${{ parameters.namespace }}
              command: get
              arguments: 'pods,daemonsets -l app.kubernetes.io/name=netprobe --ignore-not-found'
              outputFormat: ''
