// ---------- Log Ingestion (Usage_CL) ----------
Usage_CL
| summarize TotalVolumeGB = sum(Quantity_d / 1000.) by bin(TimeGenerated, 1d)
| project Day = TimeGenerated, TotalVolumeGB
| order by Day asc

// ---------- Frontdoor Traffic ----------
FrontdoorAccessLog_CL
| summarize count() by bin(TimeGenerated, 1d)
| order by TimeGenerated asc

// ---------- Error Count ----------
let errorType = ': ERROR';
ContainerLog_CL
| join kind=inner (
    KubePodInventory_CL
    | project ContainerID_s, PodName = Name_s, ControllerKind_s, ControllerName_s, Namespace_s
    | distinct *
  ) on ContainerID_s
| project TimeGenerated, Namespace_s, PodName, LogEntry_s, ControllerKind_s, ControllerName_s
| where LogEntry_s has_cs errorType
| summarize Count = count() by bin(TimeGenerated, 1d)
| order by TimeGenerated asc
| render timechart

// ---------- Error count by Tenant ----------
let paramPodNamePrefix = 'wso2is-deployment';
let errorTypeT = 'ERROR';
let errorRegex = '.*iam-cloud-.* : ERROR {.*} .*';
ContainerLog_CL
| join kind=inner (
    KubePodInventory_CL
    | project ContainerID_s, PodName = Name_s, ControllerKind_s, ControllerName_s, Namespace_s
    | where PodName contains paramPodNamePrefix
    | distinct *
  ) on ContainerID_s
| where LogEntry_s has_cs errorTypeT
| where LogEntry_s matches regex errorRegex
| where LogEntry_s !contains "Error when setting claim"
| where LogEntry_s !contains "No message body reader has been found for class java.lang.String, ContentType: application/octet-stream"
| where LogEntry_s !contains "Error occurred while getting database type from DB connection org.wso2.carbon.user.core.UserStoreException: Error occurred while getting database type from DB connection"
| where LogEntry_s !contains "Error occurred while getting database type from DB connection org.wso2.charon3.core.exceptions.CharonException: Error occurred while getting database type from DB connection"
| where LogEntry_s !contains "This password has been used in recent history. Please choose a different password"
| where LogEntry_s !contains "Error occurred while getting the OAuth App tenantDomain by Consumer key: CHOREO_SYSTEM_APP_MANAGER"
| where LogEntry_s !contains "ERROR {org.wso2.carbon.identity.oauth2.grant.jwt.JWTBearerGrantHandler} - JSON Web Token is issued before the allowed time."
| where LogEntry_s !contains "ERROR {org.wso2.carbon.identity.input.validation.mgt.listener.InputValidationListener} - Failed to validate username for user."
| where LogEntry_s !contains "Caused by: java.sql.BatchUpdateException: Violation of UNIQUE KEY constraint 'UQ__UM_USER___BBB8EC7E9AE1457C'. Cannot insert duplicate key in object 'dbo.UM_USER_ROLE'."
| where LogEntry_s !contains "{org.wso2.carbon.identity.application.authentication.framework.config.model.graph.openjdk.nashorn.JsOpenJdkNashornGraphBuilder} - Event handler : authenticationOptions is not a function"
| where LogEntry_s !contains "{org.wso2.carbon.identity.application.authentication.framework.config.model.graph.js.JsClaims} - Error when getting claim : http://wso2.org/claims/identity/country of user"
| where not (LogEntry_s matches regex @"Tenant:\s*\[lilt\].*?iam-cloud-carbon\s*:\s*ERROR\s*\{org.wso2.carbon.identity.application.authentication.framework.config.model.graph.js.JsLogger\}")
| sort by TimeGenerated asc
| project TimeGenerated, LogEntry_s
| parse LogEntry_s with * "Tenant: [" TenantName "]" *
| where isnotempty(TenantName)
| summarize LogCount = count() by TenantName

// ---------- Traffic by Tenant ----------
FrontdoorAccessLog_CL
| extend reqUri = tostring(requestUri_s)
| extend tenant_from_path = extract(@"/t/([^/]+)", 1, reqUri)
| extend custom_domain = extract(@"https?://([^/:]+)", 1, reqUri)
| extend tenant =
    case(
        isnotempty(tenant_from_path), tenant_from_path,
        isnotempty(custom_domain) and custom_domain !contains "asgardeo.io", custom_domain,
        ""
    )
| where isnotempty(tenant)
| summarize request_count = count() by bin(TimeGenerated, 12h), tenant
| order by TimeGenerated asc
| render columnchart
